"""IMPORTANT. Do this first to setup vim-plug
" 1. Follow instructions in https://github.com/junegunn/vim-plug#installation.
"    (put the plug.vim file in ~/.vim/autoload directory)
"""

"""IMPORTANT. If using neovim do the following.
" 1. Install neovim using `brew install neovim`
" 2. create ~/.config/nvim/init.vim with these contents (without the comment quotes):
"
"    set runtimepath^=~/.vim runtimepath+=~/.vim/after
"    let &packpath = &runtimepath
"    source ~/.vimrc
"
"""

"""IMPORTANT. For python stuff, make sure to install the following.
" 1. flake8: `pip install flake8`
" (2. neovim: `pip install neovim`)
"""

"""IMPORTANT. Do this after finishing the above steps.
" 1. Open vim/nvim and run :PlugInstall
"""

let mapleader = ","
set nocompatible
filetype off

"""Start of Plug stuff
call plug#begin('~/.vim/plugged')
Plug 'easymotion/vim-easymotion'
Plug 'ervandew/supertab'
Plug 'flazz/vim-colorschemes'
Plug 'haya14busa/incsearch-easymotion.vim'
Plug 'haya14busa/incsearch.vim'
Plug 'kien/rainbow_parentheses.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'

Plug 'vhdirk/vim-cmake'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'guns/vim-sexp', { 'for': 'clojure' }
Plug 'liquidz/vim-iced', {'for': 'clojure'}
Plug 'tpope/vim-sexp-mappings-for-regular-people', { 'for': 'clojure' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'liquidz/vim-iced-project-namespaces', {'for': 'clojure', 'on': 'IcedBrowseNamespace'}
Plug 'liquidz/vim-iced-function-list', {'for': 'clojure', 'on': 'IcedBrowseFunction'}


Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-syntastic/syntastic'
Plug 'terryma/vim-multiple-cursors'
Plug 'ntpeters/vim-better-whitespace'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mklabs/split-term.vim'
Plug 'neovimhaskell/haskell-vim'
Plug 'itchyny/vim-haskell-indent'
Plug 'ndmitchell/ghcid', { 'rtp': 'plugins/nvim' }
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'let-def/ocp-indent-vim'
Plug 'rizzatti/dash.vim'
Plug 'JuliaEditorSupport/julia-vim'
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
call plug#end()
"""End of Plug stuff

filetype plugin indent on
syntax on

set tabstop=4
set expandtab
set shiftwidth=4
set tw=90
set mouse=a
set ic
set incsearch
set ruler
set nofoldenable

"""Color scheme
colorscheme jellybeans

"""Setup backup/swap dir
set backup
set swapfile
set backupdir=~/.vim-tmp
set directory=~/.vim-tmp

match ErrorMsg '\%>100v.\+'
match ErrorMsg '\s\+\%#\@<!$'
autocmd InsertLeave * redraw!

"""Syntastic
let g:syntastic_mode_map = { 'passive_filetypes': ['cpp'] }
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
highlight SyntasticError guibg=#2f0000
highlight SyntasticErrorSign guifg=white guibg=red
highlight SyntasticErrorLine guifg=white guibg=red
highlight SyntasticWarningLine guifg=white guibg=red
let g:syntastic_enable_signs = 1
nnoremap <leader>en :silent! lnext<CR>
nnoremap <leader>ep :silent! lprev<CR>

"""Rainbow parentheses everywhere
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['white',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
autocmd VimEnter * RainbowParenthesesToggle
autocmd Syntax * RainbowParenthesesLoadRound
autocmd Syntax * RainbowParenthesesLoadSquare
autocmd Syntax * RainbowParenthesesLoadBraces

"""LanguageClient
" See https://github.com/autozimu/LanguageClient-neovim
"     https://github.com/haskell/haskell-ide-engine#using-hie-with-vim-or-neovim
"""
function LC_maps()
    if has_key(g:LanguageClient_serverCommands, &filetype)
        nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<cr>
        nnoremap <buffer> <silent> W :pclose<cr>
        nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
        nnoremap <buffer> <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
    endif
endfunction
autocmd FileType haskell call LC_maps()
let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie-wrapper'],
    \ }
nnoremap <F5> :call LanguageClient_contextMenu()<CR>
map <Leader>lk :call LanguageClient#textDocument_hover()<CR>
map <Leader>lg :call LanguageClient#textDocument_definition()<CR>
map <Leader>lr :call LanguageClient#textDocument_rename()<CR>
map <Leader>lf :call LanguageClient#textDocument_formatting()<CR>
map <Leader>lb :call LanguageClient#textDocument_references()<CR>
map <Leader>la :call LanguageClient#textDocument_codeAction()<CR>
map <Leader>ls :call LanguageClient#textDocument_documentSymbol()<CR><Paste>

hi link ALEError Error
hi Warning term=underline cterm=underline ctermfg=Yellow gui=undercurl guisp=Gold
hi link ALEWarning Warning
hi link ALEInfo SpellCap
let g:ale_set_highlights = 0
let g:ale_sign_error = 'x'
let g:ale_sign_warning = 'w'
let g:ale_lint_on_enter = 0
let g:LanguageClient_diagnosticsSignsMax = 0
let g:LanguageClient_diagnosticsEnable=0

"""Easymotion
map <Leader> <Plug>(easymotion-prefix)
nmap <Leader>, <Plug>(easymotion-overwin-f)
map  <Leader>f <Plug>(easymotion-bd-f)
nmap <Leader>f <Plug>(easymotion-overwin-f)
map <Leader>/ <Plug>(incsearch-easymotion-/)
map <Leader>? <Plug>(incsearch-easymotion-?)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)
let g:EasyMotion_startofline = 0 " keep cursor column when JK motion

"""C++
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++17 -stdlib=libc++'

"""Python
"(Remember to pip install flake8!)
let g:syntastic_python_checkers = ['flake8']

"""Haskell
let g:ghcid_command = 'ghcid -c "stack ghci --no-test"'
let g:haskell_indent_disable = 1  " Use vim-haskell-indent instead
autocmd Filetype haskell setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

"""Tabs
nnoremap <leader>tn :silent! tabn<CR>
nnoremap <leader>tp :silent! tabp<CR>
nnoremap <leader>to :silent! tabnew<CR>

"""NERDTree
nnoremap \n :NERDTreeToggle<CR>

"""Fzf
nnoremap \\ :silent! Buffers<CR>
nnoremap \f :silent! Files<CR>
nnoremap \l :silent! Lines<CR>
nnoremap \s :silent! Ag<CR>

"""Unhighlight last search on escape
nnoremap <Esc> :nohlsearch<CR><Esc>

"""Highlight rows which are too long
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%101v.\+/

"""Set highlight color for search
highlight Search cterm=NONE ctermfg=black ctermbg=white

"""Disable auto-wrapping long lines
set formatoptions-=t

"""Custom functions
func! DeleteTrailingWS()
    exe "normal mz"
    %s/\s\+$//ge
    exe "normal 'z"
endfunc
autocmd BufWrite * :call DeleteTrailingWS()

"With cursor on line call :Underline
function! s:Underline(chars)
    let chars = empty(a:chars) ? '-' : a:chars
    let nr_columns = virtcol('$') - 1
    let uline = repeat(chars, (nr_columns / len(chars)) + 1)
    put =strpart(uline, 0, nr_columns)
endfunction
command! -nargs=? Underline call s:Underline(<q-args>)

set hidden

"Shorcuts for clojure filetype
autocmd filetype clojure map <leader>cc <Plug>(iced_connect)
autocmd filetype clojure map <leader>ei <Plug>(iced_eval)<Plug>(sexp_inner_element)
autocmd filetype clojure map <leader>ee <Plug>(iced_eval)<Plug>(sexp_outer_list)
autocmd filetype clojure map <leader>en <Plug>(iced_eval_ns)
autocmd filetype clojure map <leader>et <Plug>(iced_eval_outer_top_list)
autocmd filetype clojure map <leader>er <Plug>(iced_eval_repl_visual)
autocmd filetype clojure map <leader>ep <Plug>(iced_print_last)
autocmd filetype clojure map <leader>eu <Plug>(iced_undef)
autocmd filetype clojure map <leader>eq <Plug>(iced_interrupt)
autocmd filetype clojure map <leader>eQ <Plug>(iced_interrupt_all)
autocmd filetype clojure map <leader>hd <Plug>(iced_clojuredocs_open)
autocmd filetype clojure map <leader>hh <Plug>(iced_command_palette)
autocmd filetype clojure map <leader>hs <Plug>(iced_popup_source_show)
autocmd filetype clojure map <leader>jb <Plug>(iced_def_back)
autocmd filetype clojure map <leader>jd <Plug>(iced_def_jump)
autocmd filetype clojure map <leader>jl <Plug>(iced_jump_to_let)
autocmd filetype clojure map <leader>== <Plug>(iced_format)
autocmd filetype clojure map <leader>=G <Plug>(iced_format_all)

"Shorcuts for cpp filetype
autocmd filetype cpp map <leader>cc :Dispatch! make -C build<CR>
autocmd filetype cpp map <leader>r :Term ./build/main<CR>
command! -nargs=+ Cppman silent! call system("tmux split-window cppman " . expand(<q-args>))
autocmd FileType cpp nnoremap <silent><buffer> K <Esc>:Cppman <cword><CR>

"Special indent configuration for javascript
autocmd FileType javascript set sw=2
autocmd FileType javascript set ts=2
autocmd FileType javascript set sts=2

"Special indent configuration for css
autocmd FileType css set sw=2
autocmd FileType css set ts=2
autocmd FileType css set sts=2

"Special indent configuration for html
autocmd FileType html set sw=2
autocmd FileType html set ts=2
autocmd FileType html set sts=2

"Auto create non-existent dirs when creating a new file
function s:MkNonExDir(file, buf)
    if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
        let dir=fnamemodify(a:file, ':h')
        if !isdirectory(dir)
            call mkdir(dir, 'p')
        endif
    endif
endfunction

augroup BWCCreateDir
    autocmd!
    autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
augroup END
