alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias ec="emacsclient -a '' -c"
alias e="emacsclient -a '' -t"

alias httpserver='python -m SimpleHTTPServer'

if [ -f ~/.custom_bash_aliases ]; then
    . ~/.custom_bash_aliases
fi
